server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db05
    username: root
    password: 1234
  redis:
    host: 192.168.129.135
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    virtual-host: /dp
    username: dianping
    password: 123456
    host: 192.168.129.135
    port: 5672
    listener:
      simple:
        acknowledge-mode: auto # 开启消费者确认机制 自动ACK
        retry:
          enabled: true # 开启消费者失败重试，参数为默认参数
          stateless: true
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug